# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16873cf613dd8c91ed442ebadece1a4ead49d33b50c6ce68fc1a7c258bcce2709356256be72742b6ca6b97ec279217a6b80b802f745034e90fca6769661e47e9

test:
  secret_key_base: 1058b37e3d2df2de24e7cdb2b83c7a176a1e97619c87fd2fdf3991fbd327a0f59c38f14c291c5285cd532d80c932cfa18f551a2c4478fc4d92fa16bb79387f6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
